apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    app: web
spec:
  volumes:
    - name: app
      emptyDir: { }
  containers:
    - name: kubernetes-intro
      image: zaglex/kubernetes-intro-web:latest
      volumeMounts:
        - name: app
          mountPath: /app
  initContainers:
    - name: web-init
      image: busybox:1.31.0
      volumeMounts:
      - name: app
        mountPath: /app
      command: ['/bin/sh']
      args: ['-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | /bin/sh']
